name: finedust
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: sunflower
      fonts:
        - asset: asset/fonts/Sunflower-Bold.ttf
          weight: 700
        - asset: asset/fonts/Sunflower-Medium.ttf
          weight: 500
        - asset: asset/fonts/Sunflower-Light.ttf
          weight: 300


